version: '2.4'

x-es:
  &es
  image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
  environment:
    - cluster.name=astrosims
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms20g -Xmx20g"
    - "discovery.zen.ping.unicast.hosts=astrosims-es"
    - "discovery.zen.minimum_master_nodes=3"
    - "node.max_local_storage_nodes=8"
  ulimits:
    memlock:
      soft: -1
      hard: -1
  networks:
    - esnet
  volumes:
    - esdata:/usr/share/elasticsearch/data

services:
  astrosims-es:
    << : *es
    container_name: astrosims-es
    expose:
      - "9200"
    ports:
      - "127.0.0.1:9200:9200"
  es:
    << : *es
    scale: 4
  astrosims:
    build: .
    image: flatironinstitute/astrosims-reproto
    networks:
      - esnet
    ports:
      - "80:8092"
    depends_on:
      - astrosims-es

volumes:
  esdata:

networks:
  esnet:
