resolver: lts-11.22
packages:
- '.'
- location:
    git: git://github.com/dylex/waimwork
    commit: 08ce12a8fbeffd7efbf5e1b1b2748893e58f7fc4
  extra-dep: true
- location: hs-hdf5
  extra-dep: true
extra-deps:
  - web-inv-route-0.1.2.1
flags:
  web-inv-route:
    snap: false
    happstack: false
